# Generated by Django 5.2.14 on 2026-08-10 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_floor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('maintenance', 'Maintenance')], default='available', max_length=20)),
                ('partitions', models.BooleanField(default=False)),
                ('complete', models.BooleanField(default=False)),
                ('partitions_no', models.PositiveIntegerField(default=0)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to='shop.floor')),
            ],
        ),
    ]
