# Generated by Django 5.2.14 on 2026-08-11 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_apartment_daily_apartment_monthly_apartment_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('daily', models.BooleanField(default=False)),
                ('monthly', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partition_item', to='shop.apartment')),
            ],
        ),
    ]
